name: Command - Release

#
# An IssueOps Command. This command provides a "/deploy <env>" command that can be used from Issue comments
# This is very similar to a Slack Slash command in intent.
#

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  command:
    name: Command
    runs-on: ubuntu-20.04
    
    # Save some actions minutes, and only execute when necessary :-)
    if: contains(github.event.comment.body, '/release ')

    steps:
      - name: Parse and Respond to Command
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const semvarRegex = /\/release gs-rel-[0-9]+.[0-9]+.[0-9]+/g;
            result = github.event.comment.body.match(semvarRegex)
            if (result && result.length > 0) {
              splitResult = result[0].split(" ")
              if (splitResult && splitResult.length > 0) {
                release = splitResult[1];              
                await github.issues.addLabels({
                  ...context.repo,
                  issue_number: context.issue.number,
                  labels: [`release/${release}`]
                });
            } else {
              console.log(`:red_circle:  Error occurred "${request ? request[1] : null}"`);
            }
