name: Command - Release

#
# An IssueOps Command. This command provides a "/deploy <env>" command that can be used from Issue comments
# This is very similar to a Slack Slash command in intent.
#

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  command:
    name: Command
    runs-on: ubuntu-20.04
    
    # Save some actions minutes, and only execute when necessary :-)
    if: startsWith(github.event.comment.body, '/release ')

    steps:
      - name: Parse and Respond to Command
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = context.payload.comment.body;
            const request = /\/release (.*)/.exec(comment);

            // Ensure request is of the format gs-rel-x.y.z
            const semvarRegex = /gs-rel-[0-9]+.[0-9]+.[0-9]+/g;
            
            if (request && request[1].match(semvarRegex)) {
              console.log(`release request "${request[1]}"`);
            
              await github.issues.addLabels({
                ...context.repo,
                issue_number: context.issue.number,
                labels: [`release/${request[1]}`]
              });
            } else {
              console.log(`:red_circle:  Error occurred "${request ? request[1] : null}"`);
            }
